### PR TITLE
Added lowercase split value #42

### LINKED ISSUE #42: Use lower case names for split values
**Is your feature request related to a problem? Please describe.**
Change split values from all caps to lower case. 
This makes file/directory naming more consistent with the split.

**Describe the solution you'd like**
TRAIN -> train
VALIDATION -> validation
TEST -> test

**Describe alternatives you've considered**
1. No change
- There's a bit of skew when it comes to mapping split value with file/dir name.

### PR DESCRIPTION
**Pull request by Samad999777**
## Description
These changes are in response to #42 
The lowercase spilt values has been enhanced in the library code. Instead of uppercase "TRAIN" "TEST" "VALIDATE", the constant allowed values are "train" "test" "validate". The images dataset folder labels are also changed. 

Fixes #42 

- [YES ] This change requires a documentation update

### CODE REVIEW

**Comment by cfezequiel** [comment]
Hi @Samad999777 , thanks for supporting TFRecorder and contributing changes. I checked out your PR and noticed that some of the tests had failed (it seems this wasn't picked up by our CI workflow). For instance, you may need to update the data file used in the test. `tfrecorder/test_data/data.csv` so that the split values are also in lowercase. Please ensure that all of the tests pass and also make sure to check off all the relevant items in the PR checklist found in `.github/PULL_REQUEST_TEMPLATE.md`.

**Comment by Samad999777** [comment]
Hi @cfezequiel, Thanks for pointing it out. I changed the labels in the csv too, but at the tests, I am getting a file not found error for the temp file that is created using mock. 
`ERROR: test_valid_records (__main__.CheckTFRecordsTest)
Tests valid case on reading multiple records.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow-recorder\lib\site-packages\mock\mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "D:/Open Source/Google/tensorflow-recorder/tfrecorder/utils_test.py", line 79, in test_valid_records
    with tempfile.TemporaryDirectory(dir='/tmp') as dir_:
  File "C:\ProgramData\Anaconda3\envs\tensorflow-recorder\lib\tempfile.py", line 780, in __init__
    self.name = mkdtemp(suffix, prefix, dir)
  File "C:\ProgramData\Anaconda3\envs\tensorflow-recorder\lib\tempfile.py", line 358, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/tmp\\tmpttj4hiod'

----------------------------------------------------------------------
Ran 2 tests in 0.054s

FAILED (errors=1)
`

I am using windows. Could that be the reason ?

**Comment by cfezequiel** [comment]
Hi @Samad999777, yes I think it's because of the temp file path. The test hardcodes the temp dir to `/tmp`. You could verify that by omitting `dir='/tmp'` in `test_valid_records`. I'd suggest running the tests in Linux shell if you have access to one.

**Comment by Samad999777** [comment]
Hey @cfezequiel i currently don't have a linux terminal availability. Would it be okay if i create a pull request and you verify the changes?

**Comment by Samad999777** [comment]
Yeah, @cfezequiel i want to create a new request since i made changes in some files and im requesting that you verify the testa, since i can't run them in my windows environment.
Would it be okay?

**Comment by cfezequiel** [comment]
@Samad999777 when you create a new PR you could try the approach I mentioned (omitting `dir='/tmp'`) and see if the tests run on your Windows machine. We have limited bandwidth to review PRs at the moment.

**Comment by Samad999777** [comment]
@cfezequiel Hey, It worked and the tests gave me 'OK' status, do you want me to upload the util_test.py with the `'dir='/tmp''` or after omitting it ?

**Comment by Samad999777** [comment]
@cfezequiel I am creating new pull request with the updated code and all tests are passing in it. Closing this one out.

**Pull request closed without merging**
