### PR TITLE
Minor fixes + explicit error when no training split found

### PR DESCRIPTION
**Pull request by lc0**
Hello everyone, 

I added an explicit error when no training split found.

A side question: you mention linting and 10/10 score, but I already see some `wrong-import-order` that I was not touching

### CODE REVIEW

**Comment by mbernico** [comment]
Thanks for the PR @lc0  - Carlos can you PTAL while I'm out.

**Comment by cfezequiel** [comment]
Hi @lc0 , thanks for submitting a PR! Could you give us more details regarding the error you encountered, specifically the Python file in which it occurred?

Also, please note that PRs for new features should be merged against our `dev` branch. We reserve merging directly to `master` for bug fixes and releases. We plan to make another release soon as `master` is several changes behind `dev`.

**Comment by lc0** [comment]
> Hi @lc0 , thanks for submitting a PR! Could you give us more details regarding the error you encountered, specifically the Python file in which it occurred?
> 
> Also, please note that PRs for new features should be merged against our `dev` branch. We reserve merging directly to `master` for bug fixes and releases. We plan to make another release soon as `master` is several changes behind `dev`.

not having exactly `TRAIN` in folder path, would yield an empty assert, that currently in code

**Comment by lc0** [comment]
@cfezequiel I am closing this one and we can continue the conversation in #51

**Pull request closed without merging**
